version: "3.9"

services:
  gradio_app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - model_server
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - GRADIO_APP_PORT=7860
      - MODEL_SERVER_HOST=model_server
      - MODEL_SERVER_PORT=8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7860" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      app_net:

  model_server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - SERVER_DEVICE=cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/model_list"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      app_net:

networks:
  app_net:
    driver: bridge
